// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAq7Nxwq_bjv-H-0KvI60aZkJ_sORyPs8',
    appId: '1:248321400997:web:b2e9f68a934b43f96bad4c',
    messagingSenderId: '248321400997',
    projectId: 'the-splendid-market',
    authDomain: 'the-splendid-market.firebaseapp.com',
    storageBucket: 'the-splendid-market.appspot.com',
    measurementId: 'G-ZTNW7J2K0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF_GwtlL12E0gw9kQdvVoKQF98PqQ35ms',
    appId: '1:248321400997:android:0e2154772bffe6af6bad4c',
    messagingSenderId: '248321400997',
    projectId: 'the-splendid-market',
    storageBucket: 'the-splendid-market.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4wR-8fRdAop4B6b8Zb9rj91SlvmDBfI',
    appId: '1:248321400997:ios:936d440570c7482e6bad4c',
    messagingSenderId: '248321400997',
    projectId: 'the-splendid-market',
    storageBucket: 'the-splendid-market.appspot.com',
    iosBundleId: 'com.realstore.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv4wR-8fRdAop4B6b8Zb9rj91SlvmDBfI',
    appId: '1:248321400997:ios:936d440570c7482e6bad4c',
    messagingSenderId: '248321400997',
    projectId: 'the-splendid-market',
    storageBucket: 'the-splendid-market.appspot.com',
    iosBundleId: 'com.realstore.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvKuUX-6jWkVJV5CpKGJNZ8qDRiy53MvE',
    appId: '1:248321400997:web:3796ad623a6d00086bad4c',
    messagingSenderId: '248321400997',
    projectId: 'the-splendid-market',
    authDomain: 'the-splendid-market.firebaseapp.com',
    storageBucket: 'the-splendid-market.appspot.com',
    measurementId: 'G-RLBYHRXXKF',
  );
}
